// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/lvisei/go-kriging-service/internal/app/api"
	"github.com/lvisei/go-kriging-service/internal/app/bll"
	"github.com/lvisei/go-kriging-service/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	ordinary := &bll.Ordinary{}
	apiOrdinary := &api.Ordinary{
		OrdinaryBll: ordinary,
	}
	routerRouter := &router.Router{
		OrdinaryAPI: apiOrdinary,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
